# Generated by Django 3.2.13 on 2022-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='content',
            field=models.TextField(default=True),
        ),
    ]
