# Generated by Django 3.2.13 on 2022-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_practice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='content',
            field=models.TextField(),
        ),
    ]
